# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Negative', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('BoxNumber', models.IntegerField()),
                ('SubjectName', models.CharField(max_length=1000)),
                ('SubjectDescription', models.CharField(max_length=10000)),
                ('Month', models.IntegerField()),
                ('Day', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('NoDate', models.CharField(max_length=10)),
                ('PhotoDescription', models.CharField(max_length=10000)),
            ],
        ),
    ]
