# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Negative', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('BoxNumber', models.IntegerField()),
                ('SubjectName', models.CharField(max_length=1000, null=True)),
                ('SubjectDescription', models.CharField(max_length=10000, null=True)),
                ('Month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('Day', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('PhotoDescription', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
