# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Negative', models.CharField(db_index=True, max_length=1000)),
                ('Quantity', models.IntegerField(null=True)),
                ('Photographer', models.CharField(db_index=True, max_length=1000, null=True)),
                ('Location', models.CharField(db_index=True, max_length=1000, null=True)),
                ('BoxNumber', models.IntegerField(db_index=True, null=True)),
                ('SubjectName', models.CharField(db_index=True, default=b'', max_length=1000, null=True)),
                ('SubjectDescription', models.CharField(db_index=True, max_length=10000, null=True)),
                ('Month', models.IntegerField(choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')], null=True)),
                ('Day', models.IntegerField(null=True)),
                ('Year', models.IntegerField(db_index=True, null=True)),
                ('PhotoDescription', models.CharField(db_index=True, max_length=10000, null=True)),
            ],
        ),
    ]
