# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='BoxNumber',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Negative',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='PhotoDescription',
            field=models.CharField(db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='SubjectDescription',
            field=models.CharField(db_index=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='SubjectName',
            field=models.CharField(db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Year',
            field=models.IntegerField(db_index=True),
        ),
    ]
