# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170509_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='NoDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='PhotoDescription',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='SubjectDescription',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='SubjectName',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
