# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20171012_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='DateCombine',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
