# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170822_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='BoxNumber',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Month',
            field=models.IntegerField(choices=[(1, b'January'), (2, b'February'), (3, b'March'), (4, b'April'), (5, b'May'), (6, b'June'), (7, b'July'), (8, b'August'), (9, b'September'), (10, b'October'), (11, b'November'), (12, b'December')], null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Year',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
