# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170822_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Negative',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
